### ISSUE TITLE
Artifacts below title

### ISSUE THREAD

**Issue by kevinpcross** [RobboRob/allsky#10]
I get a straight 1 or 2 pix width line below the title area. I estimate Y~200 on position from eyeball. On that line at the right border of the image are red and blue lines that look like a graph of some sort.  Is this normal? It happens on both a V2 and HQ camera and I've tried 2 pi3 boards. Everything else works fine but haven't tested FTP yet.
![image](https://user-images.githubusercontent.com/12113866/89246999-2e468780-d5c1-11ea-95d5-3cbc0ea16199.png)

**Comment by DarKOrange75** [comment]
This issue is related to raspistill the command used by AllSky to take pictures, not the AllSky software itself. If a fix comes, it will be from the Raspistill developpers.

**Comment by RobboRob** [comment]
The lines only appear when you switch on Image Details. Switch it off and these lines disappear...

**Comment by RobboRob** [comment]
case closed, this is not something I can fix. It is part of the raspistill behaviour...

**Comment by kevinpcross** [comment]
Thanks for following through and trying. I discovered that they are not there when details are turned off.
