### ISSUE TITLE
Suggestion - Not and issue: RaspAP Hotpoint + allsky

### ISSUE THREAD

**Issue by kevinpcross** [RobboRob/allsky#11]
Before I found allsky I was setting up RaspAP as a hotpoint to extend my network and provide a mobile network for future star parties. Long story short is I wanted my brick to do more then provide connection, hense allsky installation. You are using RaspAP for the GUI but without any hotpoint ability. It seems like it could be added easily but I haven't got the separate installs to work with each other since the stomp on the raspAP configuration files. I'm slowly working through them to see how to consolidate and get both working, but I'm not sure if your code specifically requires the "allsky" host name. Any guidance or hints on how to achieve this would be great.

 It would be a great little box to place out to record the observation session sky conditions while providing a service with the two applications combined. Provide an admin button to produce intermediate daily products such as trails and timelapse at the end of the the observation.

**Comment by DarKOrange75** [comment]
Hi, this is a fork to make the main project work with Raspberry HQ cameras. I suggest you post your question on the main project board.
