### ISSUE TITLE
Max Exposure to be re-instated

### ISSUE THREAD

**Issue by robertpascale** [RobboRob/allsky#4]
In the original project, the concept of Max Exposure when being used is important in order to preserve the duration consistency during the timelapse sequences, and in addition, can stop too many images being taken.

For example, with a sensitive camera, you might be able to geetnerate in image in 10 seconds, but that varies up to 30 seconds. You don't want to take 3 times as many images when it's brighter. You want consistent gaps, hence the "max exposure".

Additionally, RASPISTILL seems to have problems consistently creating exposures of the same duration (eg. I request 15 seconds, but the images are 10.2 seconds). I then generate too many images.

Please let me know your thoughts on reinstating the old code/logic that can maintain a "Max Exposure".
I'm happy to attempt to make the code changes, but am interested in discussing the issue.

**Comment by DarKOrange75** [comment]
Thank you Rob for this very hard work. Max exposure would work only if it was possible to use autoexposure at night with the raspberry HQ camera but so far I've been unsucessful hence I use a fixed exposure.

**Comment by robertpascale** [comment]
Agreed - the auto-exposure is not likely to be able to work any time soon based on what I can see, so this is a bit of a moot point now. Closing.
