### ISSUE TITLE
Image not parsing

### ISSUE THREAD

**Issue by ciberjohn** [RobboRob/allsky#8]
Hi. 
Apologies for bring this up to you, but I trust I have done something less correct to get this when trying to admin (or even from the public URL):
![image](https://user-images.githubusercontent.com/16627800/88559391-aabaf280-d024-11ea-8feb-809478f29bfc.png)

Any suggestions would be welcomed.

**Comment by ciberjohn** [comment]
Here is a more specific example:
http://allsky/current/liveview-image.jpg?_ts=1595863001611

**Comment by RobboRob** [comment]
Url you provide didn’t work...

Looks like your ll sky service is not working. Try to execute:

./allsky_RPiHQ.sh

This starts the service manually...

**Comment by RobboRob** [comment]
This issue should be fixed now. Do a new install of the gui and it should be ok...
